### ISSUE TITLE
Replace usages of ugettext_lazy with gettext_lazy

### ISSUE THREAD

**Issue by thembow** [DMOJ/django-slack-integration#2]
#https://github.com/DMOJ/online-judge/issues/2066
Looked into the issue over there but couldn't find any instances of the bad import on the main repo, but did see it over here, specifically in the models+apps.py.
Will make a pull request and fix

**Comment by int-y1** [comment]
There's also `ugettext` which can be replaced by `gettext`. This affects `slack_integration/log.py` and `slack_integration/views/channels.py`.
